name: build and deploy

on:
  push:
    branches:
    - master

jobs:
  build_deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: setup Hugo
      uses: peaceiris/actions-hugo@v2.2.1
      with:
        hugo-version: '0.58.3'
        extended: true
    - name: build
      run: hugo --gc --minify --cleanDestinationDir
    - name: deploy
      uses: SamKirkland/FTP-Deploy-Action@1.5.0
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
        LOCAL_DIR: ./public
        ARGS: --delete
      if: success()
